### ISSUE TITLE
Repository URL

### ISSUE THREAD

**Issue by almereyda** [JustAdam/docker-gen-swarm#1]
You could add the URL of [the associated blog post](http://www.before.no/2015/04/using-docker-gen-with-a-swarm-cluster/) directly to this repository, or I could issue a PR for `README.md`.

Which would you prefer, lacking a determining `CONTRIBUTING.md`?

**Comment by JustAdam** [comment]
It is already there; in the first paragraph, second sentence under "docker-gen and Docker Swarm".  But feel free to open a PR if it isn't clear enough :)

**Comment by almereyda** [comment]
Wow! I haven't seen **this**. Really.

**Comment by JustAdam** [comment]
Not sure what to make of that comment ;)
